name: ci
on: [push]
jobs:
  checkout-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: the echo
        run: |
          cat $GITHUB_EVENT_PATH
          first_line=$(echo "${{ github.event.head_commit.message }}" | tr '\n' '\f' | sed -e 's/^\([^\f]*\).*$/\1/')
          echo "[$first_line](${{ github.event.head_commit.url }})"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
