name: ci
on: [push]
jobs:
  checkout-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: the echo
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.ref: ${{ github.ref }}
          echo github.event.head_commit.message: ${{ github.event.head_commit.message }}
          cat $GITHUB_EVENT_PATH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
