name: ci
on: [push]
jobs:
  checkout-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: the echo
        run: |
          cat $GITHUB_EVENT_PATH
          echo "github.event.head_commit.message: ${{ github.event.head_commit.message }}"
          PR_NUMBER=$(echo "${{ github.event.head_commit.message }}" | tr '\n' '\r' | sed -e 's/Merge pull request #\(.*\) from .*/\1/')
          echo "PR_NUMBER: $PR_NUMBER"
          PR_TITLE=$(echo "${{ github.event.head_commit.message }}" | tr '\n' '\r' | sed -e 's/^.*\r\r\(.*\)$/\1/')
          echo "PR_TITLE: $PR_TITLE"
          echo github.event.repository.pulls_url: ${{ github.event.repository.pulls_url }}
          PR_URL=$(echo "${{ github.event.repository.pulls_url }}" | sed -e 's!{/number}!/'$PR_NUMBER'!')
          echo "PR_URL: $PR_URL"
          echo "#$PR_NUMBER: $PR_TITLE ($PR_URL)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
