name: ci
on: [push]
jobs:
  checkout-v2:
    steps:
      - uses: actions/checkout@v2
      - run: "echo ${{ github.event.number }}"
      - run: "echo ${{ github.event.title }}"
      - run: "echo ${{ github.event.html_url }}"
      - run: "echo ${{ github.event.pull_request.number }}"
      - run: "echo ${{ github.event.pull_request.title }}"
      - run: "echo ${{ github.event.pull_request.html_url }}"

  checkout-v3:
    steps:
      - uses: actions/checkout@v3
      - run: "echo ${{ github.event.number }}"
      - run: "echo ${{ github.event.title }}"
      - run: "echo ${{ github.event.html_url }}"
      - run: "echo ${{ github.event.pull_request.number }}"
      - run: "echo ${{ github.event.pull_request.title }}"
      - run: "echo ${{ github.event.pull_request.html_url }}"
