name: ci
on: [push]
jobs:
  checkout-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: the echo
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.ref: ${{ github.ref }}
          echo github.event.number: ${{ github.event.number }}
          echo github.event.title: ${{ github.event.title }}
          echo github.event.html_url: ${{ github.event.html_url }}
          echo github.event.pull_request.number: ${{ github.event.pull_request.number }}
          echo github.event.pull_request.title: ${{ github.event.pull_request.title }}
          echo github.event.pull_request.html_url: ${{ github.event.pull_request.html_url }}
          gh pr view
          echo GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  checkout-v3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: the echo
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.ref: ${{ github.ref }}
          echo github.event.number: ${{ github.event.number }}
          echo github.event.title: ${{ github.event.title }}
          echo github.event.html_url: ${{ github.event.html_url }}
          echo github.event.pull_request.number: ${{ github.event.pull_request.number }}
          echo github.event.pull_request.title: ${{ github.event.pull_request.title }}
          echo github.event.pull_request.html_url: ${{ github.event.pull_request.html_url }}
          gh pr view
          echo GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  checkout-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: the echo
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.ref: ${{ github.ref }}
          echo github.event.number: ${{ github.event.number }}
          echo github.event.title: ${{ github.event.title }}
          echo github.event.html_url: ${{ github.event.html_url }}
          echo github.event.pull_request.number: ${{ github.event.pull_request.number }}
          echo github.event.pull_request.title: ${{ github.event.pull_request.title }}
          echo github.event.pull_request.html_url: ${{ github.event.pull_request.html_url }}
          gh pr view
          echo GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH
          cat $GITHUB_EVENT_PATH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
